### ISSUE TITLE
CTRL+A Insanity!

### ISSUE THREAD

**Issue by Dekken** [CBPP/cbpp10-amd64#2]
Please PLEASE tell me how to disable this ctrl-A window madness

I just want it to select all.
This seems to be a thing in newer Ubuntu(s) also and it really makes me weep.

**Comment by Dekken** [comment]
It would appear to be caused by "Terminator"

it only happens when Terminator is open, and messing the terminator keybindings has resolved it.

I think the "hide window" was showing as "Ctrl-Shift-A" but really it was just "Ctrl-A"

**Comment by Kurgol** [comment]
It looks like this is caused by a change in syntax in the terminator config file. It used to be <Control> but the documentation says it's now <Ctrl>. 

This is actually in the cbpp-configs repository, I will submit a PR to fix it. 

https://github.com/CBPP/cbpp-configs/blob/master/cbpp-configs/data/etc/skel/.config/terminator/config

**Comment by Dekken** [comment]
Excellent!

**Comment by Kurgol** [comment]
my initial hypothesis is bunk. It's bound as `control + shift + a` in preferences, but triggers on `ctrl + a` - I think the problem is deeper than I originally thought.

**Comment by Dekken** [comment]
it's quite bizarre indeed!
